package com.abc.salesinventory.model.newpackage;
// Generated Jun 19, 2014 10:37:25 PM by Hibernate Tools 3.6.0



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private String id;
     private User user;
     private Role role;

    public UserRole() {
    }

    public UserRole(String id, User user, Role role) {
       this.id = id;
       this.user = user;
       this.role = role;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


